repos:
- repo: https://github.com/psf/black
  rev: 24.1.0
  hooks:
    - id: black
      language_version: python3
      args: [--config=pyproject.toml]

- repo: https://github.com/pycqa/isort
  rev: 5.13.0
  hooks:
    - id: isort
      name: isort (python)
      args: [--settings-path=pyproject.toml]

# To bypass pre-commit hooks, use:
# git commit -m "your message" --no-verify
# OR
# SKIP=black,isort git commit -m "your message" 